### ISSUE TITLE
tokenizing json files

### ISSUE THREAD

**Issue by tansaku** [Martin-Hausleitner/vscode-tokenizer-gpt3-codex#1]
Great project!  I have it working on files like python files but doesn't seem to work on json files - is that intentional? Or am I just doing something wrong?

Here's my vscode version

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

I'm on v0.0.1 of your plugin

**Comment by Martin-Hausleitner** [comment]
I'm not revising the project anymore. Ideally, it should work with every file. Otherwise, feel free to clone it and try to fix it yourself.
